---
- name: Web Server Setup
  hosts: all
  become: true
  gather_facts: true
  vars:
    web_user: "{{ 'www-data' if ansible_os_family == 'Debian' else 'apache' }}"
  tasks:
    - name: Install Nginx (Ubuntu)
      ansible.builtin.apt:
       name: nginx
       state: present
      when: ansible_os_family == "Debian"

    - name: Install Apache (Amazon Linux)
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_os_family == "Amazon"

    - name: Create a web root directory
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        owner: "{{ web_user }}"
        mode: '0755'
    
    - name: Deploy a sample index.html
      ansible.builtin.template:
        src: ../files/index.html
        dest: /var/www/html/index.html
        owner: "{{ web_user }}"
        mode: '0644'

    - name: Start and enable web service
      ansible.builtin.service:
        name: "{{'nginx' if ansible_os_family == 'Debian' else 'httpd'}}"
        state: started
        enabled: true

    - name: Open HTTP port in firewall (Ubuntu)
      ansible.builtin.ufw:
        rule: allow
        port: '80'
        proto: tcp
      when: ansible_os_family == "Debian"

    - name: Open HTTP port in firewall (Amazon Linux)
      ansible.builtin.firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
        immediate: yes
      when: ansible_os_family == "Amazon"